// import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/Navbar";
// import Link from "next/link";
// import Navbar from "~/components/Navbar";
import type { NextPageWithLayout } from "./_app";
import Layout from "~/components/Layout";
import type { ReactElement } from "react";
import Login from "~/pages/Login";

// import { api } from "~/utils/api";

const Page: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Fit Collector</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Login />
    </>
  );
};

Page.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Page;
