import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import {SignOutButton, SignInButton, useUser} from "@clerk/nextjs";
import { api } from "~/utils/api";
import { Collection } from "@prisma/client";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.collections.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          {!user.isSignedIn && <SignInButton />}
          {!!user.isSignedIn && <SignOutButton />}
        </div>
        <div>
        
        {data?.map((collection: Collection) => <div key={collection.id}>{collection.name}</div>)}
        </div>
      </main>
    </>
  );
};

export default Home;
